tap 'homebrew/core'
tap 'homebrew/services'
tap 'thoughtbot/formulae'
brew 'ripgrep'
brew 'the_silver_searcher'
brew 'vim'
brew 'tmux'
brew 'ctags'
brew 'hub'
brew 'bash'
brew 'git'
brew 'ccat'
brew 'fzf'
brew 'tmuxinator'
brew 'tmuxinator-completion'

tap 'homebrew/cask-versions'
cask_args appdir: '/Applications'
cask 'iterm2'
cask 'alacritty'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'safari-technology-preview'
cask '1password'
cask 'dash'
cask 'visual-studio-code'
cask 'simplenote'
cask 'maccy'

tap 'homebrew/cask-fonts'
cask 'font-source-code-pro'
cask 'font-fira-code'
cask 'font-fira-mono'
