#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "spacemacs-theme"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    guifont = "FiraCode Nerd Font Mono:h12"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"
    project_rooter_patterns = ['.git/', 'package.json', '!node_modules/', '.engines/']
    project_rooter_outermost = false
    filemanager = "defx"
    relativenumber = false

[[layers]]
name = "core"
filetree_show_hidden = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "ctrlspace"
enable-spacevim-styled-keys = true

[[layers]]
name = "fzf"

[[layers]]
name = 'git'
git_plugin = "fugitive"

[[layers]]
name = 'VersionControl'

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#ruby"
enabled_linters = ['rubocop']

[[layers]]
name = "lang#extra"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#json"

[[layers]]
name = "gtags"
gtagslabel = "ctags"

[[layers]]
name = "tmux"

[[layers]]
name = "tools#dash"

[[layers]]
name = "tools"

[[layers]]
name = "lsp"
filetypes = [
  "css",
  "html",
  "typescript"
]

[[custom_plugins]]
repo = "colepeters/spacemacs-theme.vim"
merged = 0

[[custom_plugins]]
repo = "roxma/nvim-yarp"

[[custom_plugins]]
repo = "roxma/vim-hug-neovim-rpc"

[[custom_plugins]]
repo = "vimwiki/vimwiki"
merged = 0
